name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Wrangler (Latest Version)
        run: npm install -g wrangler

      - name: Publish to Cloudflare Workers
        run: wrangler publish --api-token=${{ secrets.CF_API_TOKEN }}
